# Generated by Django 5.1.1 on 2024-09-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=200)),
                ('farm_owner', models.CharField(max_length=200)),
                ('farm_location', models.CharField(max_length=200)),
            ],
        ),
    ]
