# Generated by Django 5.1.1 on 2024-10-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_farm_farm_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farm_brand',
            field=models.ImageField(default='defaultlogo.jpg', upload_to='logos'),
        ),
    ]
