# Generated by Django 5.1.1 on 2024-10-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_farm_farm_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_brand',
            field=models.ImageField(default='defaultlogo.jpg', upload_to='farm_logos'),
        ),
    ]
