# Generated by Django 5.1.1 on 2024-11-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_alter_farm_farm_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
