# Generated by Django 5.1.1 on 2024-10-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=200)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
