# Generated by Django 5.1.1 on 2024-09-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='negative_quant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='positive_quant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='batch',
            name='uncertainty_quant',
            field=models.IntegerField(default=0),
        ),
    ]
