# Generated by Django 5.1.1 on 2024-09-27 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_batch_negative_quant_batch_positive_quant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='prior_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhos', to='batch.batch'),
        ),
    ]
