# Generated by Django 5.1.1 on 2024-09-27 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_batch_prior_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='prior_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derivative', to='batch.batch'),
        ),
    ]
