# Generated by Django 5.1.1 on 2024-10-02 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_alter_batch_prior_batch'),
        ('season', '0002_season_farms'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='season.season'),
        ),
    ]
