# Generated by Django 5.1.1 on 2024-10-02 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0005_batch_season'),
        ('season', '0002_season_farms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='season.season'),
        ),
    ]
