# Generated by Django 5.1.1 on 2024-10-12 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0006_alter_batch_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shaping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shaping_description', models.CharField(max_length=100)),
                ('shaping_acronym', models.CharField(max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='batch',
            name='animal_type',
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_shaping',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='batch.shaping'),
        ),
    ]
