# Generated by Django 5.1.1 on 2024-10-13 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0007_shaping_remove_batch_animal_type_batch_batch_shaping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_acronym', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_acronym', models.CharField(default='', max_length=50)),
                ('protocol_duration', models.IntegerField()),
                ('gnrh', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1)),
                ('presync', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1)),
                ('protocol_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='batch.supplier')),
            ],
        ),
    ]
