# Generated by Django 5.1.1 on 2024-10-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0008_supplier_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol',
            name='protocol_acronym',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
