# Generated by Django 5.1.1 on 2024-10-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0009_alter_protocol_protocol_acronym'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_acronym',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='batch',
            name='batch_maternity',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea'), ('H', 'Heterogêneo')], default='', max_length=1),
        ),
    ]
