# Generated by Django 5.1.1 on 2024-10-13 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0010_batch_batch_acronym_batch_batch_maternity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_maternity',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea'), ('H', 'Heterogêneo')], max_length=1),
        ),
    ]
