# Generated by Django 5.1.1 on 2024-10-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0011_alter_batch_batch_maternity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shaping',
            old_name='shaping_description',
            new_name='shaping_name',
        ),
    ]
