# Generated by Django 5.1.1 on 2024-10-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0015_alter_batch_dg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='dg_date',
            field=models.DateField(blank=True),
        ),
    ]
