# Generated by Django 5.1.1 on 2024-10-23 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0016_alter_batch_dg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='dg_date',
            field=models.DateField(blank=True, default=datetime.date(1500, 1, 1)),
        ),
    ]
