# Generated by Django 5.1.1 on 2024-10-23 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0019_alter_batch_protocol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='protocol',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='batch.protocol'),
        ),
    ]
