# Generated by Django 5.1.1 on 2024-10-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0021_alter_batch_dg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='recurrence_quant',
            field=models.IntegerField(default=0),
        ),
    ]
