# Generated by Django 5.1.1 on 2024-11-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0025_batch_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='batch_shaping',
        ),
        migrations.AlterField(
            model_name='batch',
            name='rating',
            field=models.DecimalField(blank=True, choices=[(2.0, '2.0'), (2.25, '2.25'), (2.5, '2.5'), (2.75, '2.75'), (3.0, '3.0'), (3.25, '3.25'), (3.5, '3.5'), (3.75, '3.75'), (4.0, '4.0'), (4.25, '4.25'), (4.5, '4.5'), (4.75, '4.75'), (5.0, '5.0')], decimal_places=2, max_digits=3, null=True, verbose_name='Rating'),
        ),
        migrations.DeleteModel(
            name='Shaping',
        ),
    ]
