# Generated by Django 5.1.1 on 2024-11-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0027_batch_batch_shapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='birth_month',
            field=models.CharField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), ('N/A', 'N/A')], max_length=3, null=True),
        ),
    ]
