# Generated by Django 5.1.1 on 2024-11-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0028_batch_birth_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('N/A', 'N/A')], max_length=3, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_maternity',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea'), ('H', 'Heterogêneo'), ('N/A', 'N/A')], max_length=3),
        ),
        migrations.RemoveField(
            model_name='batch',
            name='birth_month',
        ),
        migrations.AddField(
            model_name='batch',
            name='birth_month',
            field=models.ManyToManyField(blank=True, to='batch.birthmonth'),
        ),
    ]
